### ISSUE TITLE
ReadME Images

### ISSUE THREAD

**Issue by Raadiah** [Radhima/PostgreSQL#1]
![table create](https://user-images.githubusercontent.com/28762555/89861135-dadac780-dbc6-11ea-8b14-a6a8bbd6ce27.png)

**Comment by Raadiah** [comment]
![list of relations](https://user-images.githubusercontent.com/28762555/89862146-27270700-dbc9-11ea-94fa-a779f9fec1d5.png)
![select shipping](https://user-images.githubusercontent.com/28762555/89862148-27bf9d80-dbc9-11ea-9e34-0ca57cb55047.png)
![table create](https://user-images.githubusercontent.com/28762555/89862151-29896100-dbc9-11ea-8b09-5067ea168651.png)

**Comment by Raadiah** [comment]
![insert values](https://user-images.githubusercontent.com/28762555/89864300-89820680-dbcd-11ea-828e-ea844eb6cdec.png)

**Comment by Raadiah** [comment]
![like](https://user-images.githubusercontent.com/28762555/89909790-45185a00-dc11-11ea-8ec1-d2df9db567b5.png)
![limit with offset](https://user-images.githubusercontent.com/28762555/89909796-48134a80-dc11-11ea-9f85-177643c1822a.png)
![limit](https://user-images.githubusercontent.com/28762555/89909801-48abe100-dc11-11ea-9e28-b0aa22074eda.png)
![order by](https://user-images.githubusercontent.com/28762555/89909804-49447780-dc11-11ea-9cb7-06bdcf0a6b43.png)
![products](https://user-images.githubusercontent.com/28762555/89909810-4a75a480-dc11-11ea-8311-d7dc98cb63fc.png)
![select_columns](https://user-images.githubusercontent.com/28762555/89909814-4c3f6800-dc11-11ea-8be7-58d80e238456.png)
![select_shipping](https://user-images.githubusercontent.com/28762555/89909819-4d709500-dc11-11ea-86c0-a36bcf69dd7b.png)
![between1](https://user-images.githubusercontent.com/28762555/89909821-4ea1c200-dc11-11ea-89ad-e2afc406255b.png)
![between2](https://user-images.githubusercontent.com/28762555/89909825-4f3a5880-dc11-11ea-988e-b58200cb141f.png)
![conditional where](https://user-images.githubusercontent.com/28762555/89909828-4fd2ef00-dc11-11ea-85ce-d25e17fbe621.png)
![customer select](https://user-images.githubusercontent.com/28762555/89909830-51041c00-dc11-11ea-877e-483f072ac271.png)
![distinct](https://user-images.githubusercontent.com/28762555/89909834-52354900-dc11-11ea-9a99-33eb31e00714.png)
![ilike](https://user-images.githubusercontent.com/28762555/89909843-53ff0c80-dc11-11ea-93a9-7f34fc654160.png)
![in](https://user-images.githubusercontent.com/28762555/89909847-5497a300-dc11-11ea-9545-be69ed9a9d06.png)

**Comment by Raadiah** [comment]
![Screenshot (102)](https://user-images.githubusercontent.com/28762555/89914576-04bbda80-dc17-11ea-83c9-b19d259a5025.png)

**Comment by Raadiah** [comment]
![group_by having](https://user-images.githubusercontent.com/28762555/90130646-a31d7c80-dd8c-11ea-8bcc-5adc85e7a7f4.png)
![group_by1](https://user-images.githubusercontent.com/28762555/90130649-a44ea980-dd8c-11ea-94ca-51b002754546.png)
![group_by2](https://user-images.githubusercontent.com/28762555/90130653-a4e74000-dd8c-11ea-9017-dfdb5a0c5b7c.png)
![left_join](https://user-images.githubusercontent.com/28762555/90130655-a57fd680-dd8c-11ea-92c1-3d859629261e.png)
![Screenshot (149)](https://user-images.githubusercontent.com/28762555/90130656-a6186d00-dd8c-11ea-84a6-e57f90278e8c.png)
![create_table](https://user-images.githubusercontent.com/28762555/90130658-a6186d00-dd8c-11ea-8d01-d70e4b828c05.png)

**Comment by Radhima** [comment]
![Screenshot (148)](https://user-images.githubusercontent.com/28762555/90132026-e678ea80-dd8e-11ea-9be8-a2d74b79ff81.png)

**Comment by Raadiah** [comment]
![left_join](https://user-images.githubusercontent.com/28762555/90132122-0dcfb780-dd8f-11ea-906d-4ac9c6e94be6.png)

**Comment by Raadiah** [comment]
![Screenshot (150)](https://user-images.githubusercontent.com/28762555/90135674-d6fca000-dd94-11ea-908e-d51baffc0a6d.png)

**Comment by Raadiah** [comment]
![Screenshot (155)](https://user-images.githubusercontent.com/28762555/90152786-08339b00-ddaa-11ea-8da4-9351f3c49e03.png)

**Comment by Raadiah** [comment]
![Screenshot (160)](https://user-images.githubusercontent.com/28762555/90221379-ee3a9c80-de2b-11ea-8d5a-c8afafb18a6a.png)
![Screenshot (159)](https://user-images.githubusercontent.com/28762555/90221385-f09cf680-de2b-11ea-98a1-fcbd67ac711c.png)

**Comment by Raadiah** [comment]
![Screenshot (161)](https://user-images.githubusercontent.com/28762555/90221826-b54ef780-de2c-11ea-92c3-0357f8ebcdea.png)

**Comment by Raadiah** [comment]
![Screenshot (163)](https://user-images.githubusercontent.com/28762555/90225814-cea77200-de33-11ea-94c0-cf52e15ce04c.png)

**Comment by Raadiah** [comment]
![Screenshot (168)](https://user-images.githubusercontent.com/28762555/90227960-3f03c280-de37-11ea-9e2f-8888b59ba5fe.png)

**Comment by Raadiah** [comment]
![Screenshot (170)](https://user-images.githubusercontent.com/28762555/90228447-0c0dfe80-de38-11ea-89c5-87dc77286053.png)

**Comment by Raadiah** [comment]
![Screenshot (172)](https://user-images.githubusercontent.com/28762555/90228709-8179cf00-de38-11ea-82b1-0f7653990494.png)
